name: NP_predictor
channels:
  - auto
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asgiref=3.2.7
  - boost=1.70.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - django=3.0.5
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.64.2
  - icu=64.2
  - joblib=0.14.1
  - jpeg=9c
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - ncurses=6.1
  - numpy=1.16.4
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=0.24.2
  - patsy=0.5.1
  - pcre=8.44
  - pillow=7.1.1
  - pip=20.0.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pycairo=1.19.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - rdkit=2019.03.3
  - readline=8.0
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - sqlparse=0.3.1
  - statsmodels=0.10.1
  - tk=8.6.10
  - wheel=0.34.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4

